language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm test
  - npm build
deploy:
  app: giffy-search
  provider: heroku
  on:
    branch: master
  api_key: c97a58a6-a5cb-44d9-b2a7-a51950464c03
