language: node_js
node_js:
- "stable"
cache:
  directories:
    - node_modules
before_script:
- npm install
script:
- npm test
- npm run build
deploy:
  provider: surge
  project: ./build/
  domain: GiFinder.surge.sh
  skip_cleanup: true
